"""empty message

Revision ID: 8f3341abfc16
Revises: 59b5e525f16c
Create Date: 2023-11-25 03:42:49.825354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3341abfc16'
down_revision = '59b5e525f16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_primas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('clasificacion', sa.String(length=80), nullable=False),
    sa.Column('unidad_medida', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('rinde', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientes_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materias_primas_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_necesaria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materias_primas_id'], ['materias_primas.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_materias_primas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('materias_primas_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_stock', sa.Integer(), nullable=False),
    sa.Column('minimo_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materias_primas_id'], ['materias_primas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_producto_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_inventario', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(length=80), nullable=False),
    sa.Column('cantidad_inventario_minimo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['address'])
        batch_op.create_unique_constraint(None, ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('reset_token')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('user_receta')
    op.drop_table('user_producto_final')
    op.drop_table('user_materias_primas')
    op.drop_table('ingredientes_receta')
    op.drop_table('receta')
    op.drop_table('materias_primas')
    # ### end Alembic commands ###
